add_newline = true

[character]      # The name of the module we are configuring is "character"
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
style = "bold blue"
utc_time_offset = "1"

[aws]
format = 'on [$symbol$profile(\($region\))]($style) '
style = "bold blue"
symbol = "ğŸ…° "

#[nodejs]
#format = "via [ğŸ¤– $version](bold green) "

[package]
format = "via [ğŸ $version](208 bold) "
