add_newline = false

# A minimal left prompt
#format = """$character"""

# move the rest of the prompt to the right
#right_format = """$all"""

[character]      # The name of the module we are configuring is "character"
success_symbol = "[âœ“](bold green)"
error_symbol = "[âœ—](bold red)"

[cmd_duration]
min_time = 500
format = "â³[$duration](bold yellow)"

[time]
disabled = false
format = "[$time]($style) "
time_format = "%T"
style = "bold blue"
utc_time_offset = "1"

[aws]
disabled = false
format = 'on [$symbol($profile )(\($region\) )]($style)'
style = "bold blue"
symbol = "ğŸ…° "

[docker_context]
disabled = false
format = "[ğŸ‹ $context](blue bold) "

[git_commit]
disabled = false
commit_hash_length = 4
tag_symbol = "ğŸ”– "

[nodejs]
format = "[â¬¢ $version](bold green) "

[package]
disabled = false
format = "[ğŸ $version](208 bold) "

